### ISSUE TITLE
home functionality missing

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/dreambuilder_game#1]
VanessaE reports home functionality form unified inventory is missing and needs to be investigated

**Comment by BuckarooBanzay** [comment]
The `sethome` mod is not present in the repo (https://github.com/minetest/minetest_game/tree/master/mods/sethome)
afaik unified-inventory checks the `sethome` priv and displays the buttons optionally

**Comment by VanessaE** [comment]
I tried adding that to my local copy of DB, but for whatever reason, it had no effect.  My copy of mtg is probably just too out-of-date (I didn't think to update DB's base files before making that last release).

**Comment by wsor4035** [comment]
this works now, however the option is still not present in unified inventory for some reason. probably should look into it some more
