### ISSUE TITLE
switch to submodules for mods

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/dreambuilder_game#2]
This game could benefit from using submodules, it makes updating _much_ easier
(yeah, i know it needs some getting used-to)

**Comment by wsor4035** [comment]
This also means we can use dependabot for pr ing mod updates

**Comment by wsor4035** [comment]
need https://github.com/minetest-game/repo_slicer/issues/3 for this, wip branch submodules

**Comment by wsor4035** [comment]
update almost all the mods i could find to submodules, and added dependabot. still need to finish off the remaining stragglers, but should be in a much better place now

**Comment by wsor4035** [comment]
seems i missed closing this a long time ago, sorry
