### ISSUE TITLE
homedecor doors not seeming to naturally flip when placed together like mtg doors 

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/dreambuilder_game#20]
reported by dicelibrarian from traintable and personally verified

![image](https://user-images.githubusercontent.com/24964441/196586956-f14373ab-a961-4dab-8d65-489b9f325565.png)

**Comment by Niklp09** [comment]
Confirmed. The placement works but the texture are not rotated

**Comment by wsor4035** [comment]
while fixed in the above commit, dreambuilder should receive a dependabot pr for this tomorrow which i will merge
