### ISSUE TITLE
Won't boot, seems to be missing dependencies

### ISSUE THREAD

**Issue by Montandalar** [mt-mods/dreambuilder_game#448]
The game wasn't starting, so I did a fresh clone with `--recurse-submodules` in case it was missing some. Nope, the in-game menu actually tells me that some mod dependencies in the game can't be satisfied:

1. `castle_tapestries` depends on `unifieddyes`, which it says is unsatisfied. Unified Dyes is clearly present on the filesystem at `mods/unifieddyes`, but the in-game mod enabler GUI doesn't show it in the list.
2. `chasms`, `df_primordial_items` and `subterrane` depend on `mapgen_helper`, which my shell couldn't find with `find -type d -name mapgen_helper` unlike with Unified Dyes.

I can't explain no. 1, perhaps it's an engine issue. No. 2 is easy and was probably missed by blindly trusting Dependabot updates.

**Comment by wsor4035** [comment]
rather interesting giving ci shows it booting. havent actually downloaded and tested

**Comment by wsor4035** [comment]
few images errors from textures that are missing, but boots for me

**Comment by wsor4035** [comment]
> 2\. `chasms`, `df_primordial_items` and `subterrane` depend on `mapgen_helper`, which my shell couldn't find with `find -type d -name mapgen_helper` unlike with Unified Dyes.

less im missing something, we dont have these mods?

**Comment by Montandalar** [comment]
The issue was actually in [Minefork](https://github.com/tsadok/minefork/). I just thought it was Dreambuilder because Minefork still has the Dreambuilder main menu backgrounds.
