### ISSUE TITLE
baked clay delay registration wrong

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/dreambuilder_game#92]
> Root problem: https://notabug.org/TenPlus1/bakedclay/src/master/init.lua#L94
> Introduced in #88

> Upstream issue: https://notabug.org/TenPlus1/bakedclay/issues/11

from @BuckarooBanzay in https://github.com/mt-mods/dreambuilder_game/pull/91

**Comment by wsor4035** [comment]
considering reverting that bakedclay pr, any thoughts?

**Comment by OgelGames** [comment]
Probably safer to revert it until it's fixed, nodes registered that way can cause weird bugs: https://github.com/pandorabox-io/pandorabox-mods/pull/1935#issuecomment-950592284

**Comment by wsor4035** [comment]
https://notabug.org/TenPlus1/bakedclay/commit/bd5ff73c19ebaeec305d1ef6e7c94846b1722510 should be coming as a dependabot pr soon. so just going to merge that when it comes over as it should fix the issue

**Comment by wsor4035** [comment]
fixed in https://github.com/mt-mods/dreambuilder_game/pull/93#event-8110998871
